package com.lucius.entity;

public class RoleTreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_tree.rid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_tree.tid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_tree.rid
     *
     * @return the value of role_tree.rid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_tree.rid
     *
     * @param rid the value for role_tree.rid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_tree.tid
     *
     * @return the value of role_tree.tid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_tree.tid
     *
     * @param tid the value for role_tree.tid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}