package com.lucius.entity;

public class Tree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.tid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.treename
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    private String treename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.url
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.pid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.tid
     *
     * @return the value of tree.tid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.tid
     *
     * @param tid the value for tree.tid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.treename
     *
     * @return the value of tree.treename
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public String getTreename() {
        return treename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.treename
     *
     * @param treename the value for tree.treename
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public void setTreename(String treename) {
        this.treename = treename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.url
     *
     * @return the value of tree.url
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.url
     *
     * @param url the value for tree.url
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.pid
     *
     * @return the value of tree.pid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.pid
     *
     * @param pid the value for tree.pid
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}