package com.lucius.mapper;

import com.lucius.entity.RoleTreeExample;
import com.lucius.entity.RoleTreeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int countByExample(RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int deleteByExample(RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int deleteByPrimaryKey(RoleTreeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int insert(RoleTreeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int insertSelective(RoleTreeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    List<RoleTreeKey> selectByExample(RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleTreeKey record, @Param("example") RoleTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_tree
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int updateByExample(@Param("record") RoleTreeKey record, @Param("example") RoleTreeExample example);
}