package com.lucius.mapper;

import com.lucius.entity.UserinfoRoleExample;
import com.lucius.entity.UserinfoRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserinfoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int countByExample(UserinfoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int deleteByExample(UserinfoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int deleteByPrimaryKey(UserinfoRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int insert(UserinfoRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int insertSelective(UserinfoRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    List<UserinfoRoleKey> selectByExample(UserinfoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserinfoRoleKey record, @Param("example") UserinfoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_role
     *
     * @mbggenerated Mon Apr 15 20:24:22 CST 2019
     */
    int updateByExample(@Param("record") UserinfoRoleKey record, @Param("example") UserinfoRoleExample example);
}